name: Build Releases

on:
  workflow_dispatch:
  push:
    'tags':
      - 'v*'

env:
  GITHUB_REF: ${{ github.ref }}
  GO_VERSION: '1.24.2'

jobs:
  build-all:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Backend Repo
        uses: actions/checkout@v4
        with:
          repository: gregtwallace/apc-p15-tool
          ref: ${{ env.GITHUB_REF }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Build All
        run: |
          python ./build_release.py

      - name: Save Zip of all targets
        uses: actions/upload-artifact@v4
        with:
          name: apc-p15-tool-release
          path: ./_out/_release
