name: Build Releases

on:
  workflow_dispatch:
  push:
    'tags':
      - 'v*'

env:
  GITHUB_REF: ${{ github.ref }}

jobs:
  build-all:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.GITHUB_REF }}
          fetch-depth: 1
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Build All
        run: |
          python ./build_release.py --gitrequired

      - name: Save Zip of all targets
        uses: actions/upload-artifact@v7
        with:
          name: apc-p15-tool-release
          path: ./_out/_release
